// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrxgx_3zcbhSFLARcnmP-RxqvrH9sNLH4',
    appId: '1:22870371310:web:07d0e642b9aa4840b23cff',
    messagingSenderId: '22870371310',
    projectId: 'pe-app-728db',
    authDomain: 'pe-app-728db.firebaseapp.com',
    storageBucket: 'pe-app-728db.firebasestorage.app',
    measurementId: 'G-5MZ0LLSMNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJwqQIEnSr-Ic2sNHj57sFg26wJwCtuvY',
    appId: '1:22870371310:android:2783dd306a33889ab23cff',
    messagingSenderId: '22870371310',
    projectId: 'pe-app-728db',
    storageBucket: 'pe-app-728db.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrxgx_3zcbhSFLARcnmP-RxqvrH9sNLH4',
    appId: '1:22870371310:web:07d0e642b9aa4840b23cff',
    messagingSenderId: '22870371310',
    projectId: 'pe-app-728db',
    authDomain: 'pe-app-728db.firebaseapp.com',
    storageBucket: 'pe-app-728db.firebasestorage.app',
    measurementId: 'G-5MZ0LLSMNX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_3mpQrQv_04j9C01L-mUjWR-7LGHKQas',
    appId: '1:22870371310:ios:a422a624596136adb23cff',
    messagingSenderId: '22870371310',
    projectId: 'pe-app-728db',
    storageBucket: 'pe-app-728db.firebasestorage.app',
    iosBundleId: 'com.example.datnProject',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_3mpQrQv_04j9C01L-mUjWR-7LGHKQas',
    appId: '1:22870371310:ios:a422a624596136adb23cff',
    messagingSenderId: '22870371310',
    projectId: 'pe-app-728db',
    storageBucket: 'pe-app-728db.firebasestorage.app',
    iosBundleId: 'com.example.datnProject',
  );

}